### ISSUE TITLE
No such command 'init'

### ISSUE THREAD

**Issue by CatalinVulcan** [planetlabs/planet-client-python#1005]

**Comment by CatalinVulcan** [comment]
It needs to be:

`planet auth init`
instead of 
`planet init`

**Comment by stephenhillier** [comment]
I know this is an old issue, but thanks for reporting and following up. I just checked, and the docs at https://planet-sdk-for-python-v2.readthedocs.io/en/stable/get-started/quick-start-guide/#step-4-sign-on-to-your-account show the correct usage (`planet auth init`). The docs may have been fixed in the meantime.

Closing, but if there are other docs/examples in our repos showing the incorrect usage feel free to re-open and drop a link.
