### ISSUE TITLE
Example on how to use client to download images/tiles for AOI

### ISSUE THREAD

**Issue by adrianalbert** [planetlabs/planet-client-python#101]
Hello,

I'm not able to find any code exemplifying how to use Planet's API client to download images. I have been able to pull information on assets available given a set of filters on AOI, dates etc. using the (only) example in the ./examples folder on this repo. But is there any documentation on how to download an item of interest via the Planet API client?

Thanks,
Adrian

**Comment by bosth** [comment]
Hi Adrian,

You can use some code like this:

```
results = client.quick_search(some_request)
for item in results.items_iter(4):
    print item['id']
    assets = client.get_assets(item).get()
    activation = client.activate(assets['analytic'])
    # wait for activation
    assets = client.get_assets(item).get()
    callback = api.write_to_file()
    body = client.download(assets['analytic'], callback=callback)
    body.await()
```

By the way, we encourage you  to use GIS StackExchange with the `planet` tag for questions so that others can see and benefit from responses!

**Comment by ischneider** [comment]
Also note the reference docs, online or for download:

https://planetlabs.github.io/planet-client-python/index.html
https://github.com/planetlabs/planet-client-python/releases/download/1.0.0/planet-docs.zip

The tricky part in the example above is 'wait for activation' and doing this in a concurrent fashion.

There is some support for this:
https://planetlabs.github.io/planet-client-python/api/reference.html#activating-and-downloading-many-assets

Using the example above as a basis for using the `Downloader`, you can just call the `download` method with the `items_iter` return value, the list of asset-types of interest and the destination location.

If you set the `on_complete` method of the `Downloader` instance to your own implementation, you can receive notification of when each download is complete.

More examples should be coming soon!

**Comment by fraukaiser** [comment]
Follwing your example I managed to write a little script that downloads analytical PSScene4Band data:
```
from planet import api
import sys,os

client = api.ClientV1(api_key= 'fc1234mynumber5678fc')

aoi = {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -148.97048950195312,
              70.14456261942247
            ],
            [
              -148.282470703125,
              70.14456261942247
            ],
            [
              -148.282470703125,
              70.41333338476161
            ],
            [
              -148.97048950195312,
              70.41333338476161
            ],
            [
              -148.97048950195312,
              70.14456261942247
            ]
          ]
        ]
      }


ubicacion = api.filters.geom_filter(aoi)
item_types = ['PSScene4Band']

request = api.filters.build_search_request(ubicacion, item_types)
results = client.quick_search(request)

for item in results.items_iter(5):             # limit to 5 files
    assets = client.get_assets(item).get()
    activation = client.activate(assets['analytic'])
    # wait for it
    assets = client.get_assets(item).get()
    callback = api.write_to_file(directory='\here\goes\my\directory', callback= None, overwrite= True)
    body = client.download(assets['analytic'], callback=callback)
    body.await()
```
However, the first time I run the script, the first file of five is downloaded to my directory. Then the following error appears
`KeyError:'location'`
... and points me to client.py. The second time I run the script it downloads the first two files of five and ends with the same error, the third time the first three and so forth.

What am I missing here?

**Comment by nilshempelmann** [comment]
Dear fraukaiser
Files are inactive in the Planet archive and needs to activated first. That takes some minutes and is the reason why you can download a new file each time you ran the script. In the example is missing a sleep loop waiting for the activation of the files. 
Here is a way to go: 
https://github.com/bird-house/flyingpigeon/blob/master/scripts/eo_fetch_planet.py
Cheers 


Envoyé depuis mon smartphone. 
-------- Message d'origine --------De : fraukaiser <notifications@github.com> Date : 04/01/2018  15:27  (GMT+01:00) À : planetlabs/planet-client-python <planet-client-python@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [planetlabs/planet-client-python] Example on how to use client to download images/tiles for AOI (#101) 
Follwing your example I managed to write a little script that downloads analytical PSScene4Band data:
from planet import api
import sys,os

client = api.ClientV1(api_key= 'fc1234mynumber5678fc')

aoi = {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -148.97048950195312,
              70.14456261942247
            ],
            [
              -148.282470703125,
              70.14456261942247
            ],
            [
              -148.282470703125,
              70.41333338476161
            ],
            [
              -148.97048950195312,
              70.41333338476161
            ],
            [
              -148.97048950195312,
              70.14456261942247
            ]
          ]
        ]
      }


ubicacion = api.filters.geom_filter(aoi)
item_types = ['PSScene4Band']

request = api.filters.build_search_request(ubicacion, item_types)
results = client.quick_search(request)

for item in results.items_iter(5):             # limit to 5 files
    assets = client.get_assets(item).get()
    activation = client.activate(assets['analytic'])
    # wait for it
    assets = client.get_assets(item).get()
    callback = api.write_to_file(directory='\here\goes\my\directory', callback= None, overwrite= True)
    body = client.download(assets['analytic'], callback=callback)
    body.await()

However, the first time I run the script, the first file of five is downloaded to my directory. Then the following error appears

KeyError:'location'

... and points me to client.py. The second time I run the script it downloads the first two files of five and ends with the same error, the third time the first three and so forth.
What am I missing here?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/planetlabs/planet-client-python","title":"planetlabs/planet-client-python","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/planetlabs/planet-client-python"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fraukaiser in #101: Follwing your example I managed to write a little script that downloads analytical PSScene4Band data:\r\n```\r\nfrom planet import api\r\nimport sys,os\r\n\r\nclient = api.ClientV1(api_key= 'fc1234mynumber5678fc')\r\n\r\naoi = {\r\n        \"type\": \"Polygon\",\r\n        \"coordinates\": [\r\n          [\r\n            [\r\n              -148.97048950195312,\r\n              70.14456261942247\r\n            ],\r\n            [\r\n              -148.282470703125,\r\n              70.14456261942247\r\n            ],\r\n            [\r\n              -148.282470703125,\r\n              70.41333338476161\r\n            ],\r\n            [\r\n              -148.97048950195312,\r\n              70.41333338476161\r\n            ],\r\n            [\r\n              -148.97048950195312,\r\n              70.14456261942247\r\n            ]\r\n          ]\r\n        ]\r\n      }\r\n\r\n\r\nubicacion = api.filters.geom_filter(aoi)\r\nitem_types = ['PSScene4Band']\r\n\r\nrequest = api.filters.build_search_request(ubicacion, item_types)\r\nresults = client.quick_search(request)\r\n\r\nfor item in results.items_iter(5):             # limit to 5 files\r\n    assets = client.get_assets(item).get()\r\n    activation = client.activate(assets['analytic'])\r\n    # wait for it\r\n    assets = client.get_assets(item).get()\r\n    callback = api.write_to_file(directory='\\here\\goes\\my\\directory', callback= None, overwrite= True)\r\n    body = client.download(assets['analytic'], callback=callback)\r\n    body.await()\r\n```\r\nHowever, the first time I run the script, the first file of five is downloaded to my directory. Then the following error appears\r\n`KeyError:'location'`\r\n... and points me to client.py. The second time I run the script it downloads the first two files of five and ends with the same error, the third time the first three and so forth.\r\n\r\nWhat am I missing here?"}],"action":{"name":"View Issue","url":"https://github.com/planetlabs/planet-client-python/issues/101#issuecomment-355295334"}}}

**Comment by fraukaiser** [comment]
Dear nilshempelmann, 

thank you for your quick reply! I modified the code accordingly and it works perfectly! 
For anyone interested: https://github.com/fraukaiser/planet-fetch-data/blob/master/PlanetDataDownloader.py

Cheers

**Comment by kmu2000** [comment]
Hello fraukaiser,

Thank you very much for the script.

I am unfortunately getting the following error:
planet.api.exceptions.InvalidAPIKey: {"message": "Please enter your API key.", "errors": []}

on the following line:
results = client.quick_search(request)

I know I am using the correct API key and unable to understand where I am going wrong. Any help would be highly appreciated.

**Comment by fraukaiser** [comment]
Hi kmu2000, 

you need to set the PLANET_API_KEY permanently as an environment variable first. 
On my Linux machine this is: 
$ gedit /etc/environment
and then set the new variable: PLANET_API_KEY='yourapikey'

Cheers

**Comment by kmu2000** [comment]
Hi fraukaiser,

Thank you for your reply.
I am using a windows machine and already set the API key as an environment
variable. The first script you posted where you were getting a key error:
"location" is working exactly in the same way as you mentioned. But for
this script, I am getting such an error. I think there is some problem in
getting the dataset by using session.get(.....).  When I try to open the
url provided here, it is asking me my username and password. On providing
those details it say that the requested item type does not exist. Any help
would be appreciated.

Best regards.

**Comment by kmu2000** [comment]
Hi fraukaiser,

The script is working fine. Sorry to bother you. I was doing a mistake.

Thank you.

**Comment by fraukaiser** [comment]
Glad it worked out!
Cheers

**Comment by foguy** [comment]
Hello everyone,
please i am working on one project with planetscope image and i want to know how to download planetscope product but unfortunately i get this error:
planet.api.exceptions.InvalidAPIKey: {"message": "Please enter your API key.", "errors": []}
and i want to know how to set PLANET_API_KEY permanently as an environment variable.
i am working on windows.
Thank you

**Comment by kmu2000** [comment]
Hi foguy,

You need to follow the steps mentioned here
https://developers.planet.com/docs/quickstart/getting-started/

**Comment by nmotlagh** [comment]
> Hi Adrian,
> 
> You can use some code like this:
> 
> ```
> results = client.quick_search(some_request)
> for item in results.items_iter(4):
>     print item['id']
>     assets = client.get_assets(item).get()
>     activation = client.activate(assets['analytic'])
>     # wait for activation
>     assets = client.get_assets(item).get()
>     callback = api.write_to_file()
>     body = client.download(assets['analytic'], callback=callback)
>     body.await()
> ```
> 
> By the way, we encourage you to use GIS StackExchange with the `planet` tag for questions so that others can see and benefit from responses!

Hello @bosth ,

I tried to use some ideas from you example code; however, I could not use the body.await() method. It seems that await is a keyword in python 3.7. Do you know what I could use instead? Or do you think I am approaching this incorrectly?

Thanks

**Comment by bosth** [comment]
@nmotlagh If you are on a recent version of the client, you should be able to use `wait` rather than `await`. The function name was change to avoid conflict with the Python keyword but the code example was written before the change so it still has `await`.

**Comment by nmotlagh** [comment]
@bosth 
Thank you! I got that working; however, now I get an error:

planet.api.exceptions.TooManyRequests: max rate reached: retry-in 200ms.

I am trying to download links of assets from an order I created. I do have a long list of links to download, so I am wondering where I should implement rate limiting?

**Comment by nmotlagh** [comment]
> @bosth
> Thank you! I got that working; however, now I get an error:
> 
> planet.api.exceptions.TooManyRequests: max rate reached: retry-in 200ms.
> 
> I am trying to download links of assets from an order I created. I do have a long list of links to download, so I am wondering where I should implement rate limiting?

Here is my attempt. Thank you for your help!
```
keep_trying = True
sleep_time = .2
while keep_trying:
    try:
        write_func = api.write_to_file(directory=str(write_path))
        response = self.client.download_location(url, callback=write_func)
        response.wait()
        keep_trying = False
    except api.exceptions.TooManyRequests as e:
        sleep(sleep_time)
        sleep_time *= 2
```

**Comment by bosth** [comment]
The rate limits on the API endpoints are listed here: https://developers.planet.com/docs/data/api-mechanics/#rate-limiting

I've not had an issue with the client causing rate limit errors assuming there is some backoff like you've done but if you are seeing it, perhaps there's an improvement needed in the client. You might want to see how the command-line tool implements waits for some prior art.

**Comment by saraswatisahoo1999** [comment]
![image](https://user-images.githubusercontent.com/64797041/155278461-5c19b924-7c8c-4b59-afec-44c93ecbcf54.png)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-52-ebc3560f62ee>](https://localhost:8080/#) in <module>()
      9 ddir = str(sys.argv[1])
     10 sdate = str(sys.argv[2])
---> 11 edate = str(sys.argv[3])
     12 limit = int(sys.argv[4])
     13 

IndexError: list index out of range

I'm getting this error.

**Comment by nmotlagh** [comment]
I suspect that’s related to the fact that you’re using jupyter lab / colab. Maybe try just hard coding in values instead of using sys.argv.
