### ISSUE TITLE
CLI `planet data asset-activate` fails with unclear error message

### ISSUE THREAD

**Issue by carlodef** [planetlabs/planet-client-python#1064]
**Expected behavior**
Activate the `basic_analytic_4b_rpc` asset of a given PSScene item with the Planet client CLI.

**Minimum, Complete, Viable Code Sample**
```console
> planet data asset-activate PSScene 20240601_111709_22_24fb basic_analytic_4b_rpc
```

**Actual behavior (describe the problem)**
It's not possible to activate then download any `basic_analytic_4b_rpc` asset with the Planet client CLI. The example above gives the following error
```
Error: asset_type_id (basic_analytic_4b_rpc) must be one of []
```

**Workaround**
Trigger activation by clicking on the activation link available at https://api.planet.com/data/v1/item-types/PSScene/items/20240601_111709_22_24fb/assets/

**Environment Information**
* macOS-10.16-x86_64-i386-64bit
* 3.9.7 (default, Oct 13 2021, 06:44:56)  [Clang 12.0.0 (clang-1200.0.32.29)]
* planet, version 2.10.0

**Installation Method**
* pip

**Comment by stephenhillier** [comment]
@carlodef thanks for reporting an issue.

I have not been able to reproduce the same error as you. Since `asset-activate` is just a wrapper around the same API call you used in the workaround, I just want to rule out some kind of temporary permission issue. Do you still see the same error? Can you confirm you're using the same credentials for CLI and the API request (check `planet auth value`)?

**Comment by carlodef** [comment]
@stephenhillier indeed my `planet auth` CLI was set with old creds that don't happen to have permissions on this item, while my workaround API call used the right creds. Apologies for the false bug report, and thanks for your help. I'm closing the issue.
