### ISSUE TITLE
Document ability to batch downloads when using multiple IDs

### ISSUE THREAD

**Issue by sarasafavi** [planetlabs/planet-client-python#126]
It would be great if we had documented examples of downloading multiple assets at a time; i.e., from a text file of multiple IDs. It would be even better if we added support for file input to `--string-in id`.

**Comment by ischneider** [comment]
While the reading of terms from a file is useful, I think for the id case specifically, we should support just getting the records by id instead of building a search.

`This means build a URL: https://api.planet.com/data/v1/item-types/<item-type>/items/<id>` and either outputing ndjson or a feature collection composed of the individual records.

If the API later supports batch get-by-id, this gets even simpler.

**Comment by sgillies** [comment]
I don't understand this enhancement proposal. `planet orders download <order_id>` will download assets from a single order. Any shell will let us loop over a list of order ids, yes? We can even use GNU parallel or something like that to download concurrently. Our API docs also instruct users to make large orders, not a number of small orders, yes? @sarasafavi maybe we can reconsider this one?

**Comment by sarasafavi** [comment]
@sgillies oh wow yes, we can safely kill this proposal. The idea predates Orders API and applied to `planet data` commands, back when Data API was the only way to download assets :)
