### ISSUE TITLE
difficulty installing on mac

### ISSUE THREAD

**Issue by dfhkvs** [planetlabs/planet-client-python#134]
Trying to follow the instructions at: https://www.planet.com/docs/api-quickstart-examples/cli/

I have python on my mac. Just installed pip 9.0.1.

When I type pip install planet, I get the following error:

![image](https://user-images.githubusercontent.com/20175054/33497723-a71122c8-d683-11e7-99df-be190bbda570.png)

Anything I am missing about how to successfully install this?

**Comment by cp16net** [comment]
This is an error because its attempting to write to protected system folder in `/Library/...`.

You have 2 options of how to install packages using pip 

1)
Use a virtual environment for the by installing virtualenv to create isolated environments for each python package you may want to use or version. The benefit here is that you do not change anything in the system that could cause problems later. https://packaging.python.org/guides/installing-using-pip-and-virtualenv/
The quick gist here is `pip install --user virtualenv` 
then goto a new directory like `mkdir ~/planetcli` 
go into that directory `cd ~/planetcli`
create a vritualenv `python -m virtualenv planet`
then activate it `source env/bin/activate`
do the same command with `sudo pip install planet`
profit from the `planet` cmd.

2)
Use sudo to install the package. While this is easier its potential to mess with things on the system is usually not the way go because the installed versions of libraries maybe forced to change by new pip installed programs. This can cause previous tools to stop working later for example.
`sudo pip install planet`

Option 1 is a typical way to use pip to install packages and i would suggest it. 
Hope this helps!

**Comment by dfhkvs** [comment]
Thank you, this was super helpful. I followed the steps on option 1 and they all worked.

However, then I tried to actually execute a ‘planet’ command (as described at https://www.planet.com/docs/api-quickstart-examples/cli/)

But, it says planet not found (see image below).

As you can see, the virtualenv has been activated. But planet does not seem to work.

Is there something simple I am doing wrong?

Dave.


[cid:EE576B00-617C-4318-83E9-8F33A99C7D1F]

On Dec 2, 2017, at 12:04 AM, Craig Vyvial <notifications@github.com<mailto:notifications@github.com>> wrote:


This is an error because its attempting to write to protected system folder in /Library/....

You have 2 options of how to install packages using pip

  1.

Use a virtual environment for the by installing virtualenv to create isolated environments for each python package you may want to use or version. The benefit here is that you do not change anything in the system that could cause problems later. https://packaging.python.org/guides/installing-using-pip-and-virtualenv/
The quick gist here is pip install --user virtualenv
then goto a new directory like mkdir ~/planetcli
go into that directory cd ~/planetcli
create a vritualenv python -m virtualenv planet
then activate it source env/bin/activate
do the same command with sudo pip install planet
profit from the planet cmd.

  1.

Use sudo to install the package. While this is easier its potential to mess with things on the system is usually not the way go because the installed versions of libraries maybe forced to change by new pip installed programs. This can cause previous tools to stop working later for example.
sudo pip install planet

Option 1 is a typical way to use pip to install packages and i would suggest it.
Hope this helps!

**Comment by geowurster** [comment]
@dfhkvs I'll update the docs to reflect this, but a much better option is to `$ pip install planet --user`.  This installs the package within a subdirectory in your home directory and avoids a bunch of potential collisions and frustrations.  The one downside is that executables are placed in a directory that is probably not already on your path.

Packages are installed here:

```
~/Library/Python/$VERSION/lib/python/site-packages/
```

and executables are installed here:

```
~/Library/Python/$VERSION/bin/
```

It looks like you're on Python 2.7 so replace `$VERSION` with `2.7`.  If that directory is not already on your `$PATH`, add this line to your `~/.bash_profile`:

```
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
```

This does the same and will handle Python upgrades and changes in username:

```
PY_USER_BIN=$(python -c "import os, site; print(os.path.join(site.getuserbase(), 'bin'))")
export PATH="${PY_USER_BIN}:${PATH}"
```

### Why is this better? ###

Using `$ pip install --user` is superior in a number of ways:

1. **The most important reason**: `$ sudo pip install` _can_ execute arbitrary code as root.  If a package cannot be installed as a [wheel](https://pythonwheels.com) the installation process executes `setup.py` directly, which means that `$ sudo pip install` is the same as `$ sudo python setup.py` for source distributions.  Incidentally, we neglected to upload a Python 2 wheel for the most recent release of this package, so a `$ sudo pip install planet` at the very least triggers this package's `setup.py` to be executed as root.
2. Using `$ sudo pip install` installs the package globally and can introduce really heinous conflicts between different versions of `pip`, `python`, and other users.
3. Installing packages in individual virtual environment is a great method for isolating specific workflows, working around conflicting dependencies, or developing new code.  In this case it probably makes the `$ planet` CLI a bit harder to use.

### Cool.  What do I do now? ###

I think your virtual environment install is incorrect because you installed `planet` within the virtual environment as `sudo`.  Unless you have a specific reason for isolating the package within a virtual environment I would recommend uninstalling all possible copies of `planet`, deleting the virtual environment you created, and then installing with the `--user` flag.  Here are the steps:

1. Re-activate the virtual environment: `$ source env/bin/activate`
2. Uninstall the `sudo` installed version of `planet`: `$ sudo pip uninstall planet`
3. Make sure no other versions of `planet` are installed in the environment: `$ pip uninstall planet`
4. Deactivate the environment: `$ deactivate`
5. Delete the environment.
6. Uninstall any lingering global `sudo` installed versions of `planet`: `$ sudo pip uninstall planet`
7. Uninstall any other lingering `planet` installations: `$ pip uninstall planet`
8. Install `planet` for your user only: `$ pip install planet --user`

If for some reason you do want to keep `planet` isolated within its own virtual environment, perform steps 1 - 5 and then:

6. Create a new environment: `$ python -m virtualenv env`
7. Activate the environment: `$ source env/bin/activate`
8. Ensure the packaging related tools contained in the environment are up to date: `$ pip install pip setuptools wheel --upgrade`
9. Install `planet` within the environment: `$ pip install planet`

**Comment by dfhkvs** [comment]
Your help is very much appreciated.

D.

Sent from my iPhone

On Dec 5, 2017, at 5:21 PM, Kevin Wurster <notifications@github.com<mailto:notifications@github.com>> wrote:


@dfhkvs<https://github.com/dfhkvs> I'll update the docs to reflect this, but a much better option is to $ pip install planet --user. This installs the package within a subdirectory in your home directory and avoids a bunch of potential collisions and frustrations. The one downside is that executables are placed in a directory that is probably not already on your path.

Packages are installed here:

~/Library/Python/$VERSION/lib/python/site-packages/


and executables are installed here:

~/Library/Python/$VERSION/bin/


It looks like you're on Python 2.7 so replace $VERSION with 2.7. If that directory is not already on your $PATH, add this line to your ~/.bash_profile:

export PATH="$HOME/Library/Python/2.7/bin:$PATH"


This does the same and will handle Python upgrades and changes in username:

PY_USER_BIN=$(python -c "import os, site; print(os.path.join(site.getuserbase(), 'bin'))")
export PATH="${PY_USER_BIN}:${PATH}"


Why is this better?

Using $ pip install --user is superior in a number of ways:

  1.  The most important reason: $ sudo pip install can execute arbitrary code as root. If a package cannot be installed as a wheel<https://pythonwheels.com> the installation process executes setup.py directly, which means that $ sudo pip install is the same as $ sudo python setup.py for source distributions. Incidentally, we neglected to upload a Python 2 wheel for the most recent release of this package, so a $ sudo pip install planet at the very least triggers this package's setup.py to be executed as root.
  2.  Using $ sudo pip install installs the package globally and can introduce really heinous conflicts between different versions of pip, python, and other users.
  3.  Installing packages in individual virtual environment is a great method for isolating specific workflows, working around conflicting dependencies, or developing new code. In this case it probably makes the $ planet CLI a bit harder to use.

Cool. What do I do now?

I think your virtual environment install is incorrect because you installed planet within the virtual environment as sudo. Unless you have a specific reason for isolating the package within a virtual environment I would recommend uninstalling all possible copies of planet, deleting the virtual environment you created, and then installing with the --user flag. Here are the steps:

  1.  Re-activate the virtual environment: $ source env/bin/activate
  2.  Uninstall the sudo installed version of planet: $ sudo pip uninstall planet
  3.  Make sure no other versions of planet are installed in the environment: $ pip uninstall planet
  4.  Deactivate the environment: $ deactivate
  5.  Delete the environment.
  6.  Uninstall any lingering global sudo installed versions of planet: $ sudo pip uninstall planet
  7.  Uninstall any other lingering planet installations: $ pip uninstall planet
  8.  Install planet for your user only: $ pip install planet --user

If for some reason you do want to keep planet isolated within its own virtual environment, perform steps 1 - 5 and then:

  1.  Create a new environment: $ python -m virtualenv env
  2.  Activate the environment: $ source env/bin/activate
  3.  Ensure the packaging related tools contained in the environment are up to date: $ pip install pip setuptools wheel --upgrade
  4.  Install planet within the environment: $ pip install planet
