### ISSUE TITLE
Assess feasibility and level of effort for using aiohttp instead of httpx

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#360]
Httpx has made some breaking changes in the year since we started using it and has not yet made it to version 1. Aiohttp is the other popular async http library. To support a decision on which http library to use going forward, let's assess the feasibility and level of effort for switching over to using aiohttp.

Areas of focus:
- Support for testing the client. Look into how much our testing paradigm would have to change (can we still mock responses?)
- Downloading an order. This functionality is an example of the most complex usage of our http library as it utilizes the Body.write() method and the http.Stream object
- Creating and downloading multiple orders. This tests the asynchronous aspects of our sdk. here's the [example](https://github.com/planetlabs/planet-client-python/blob/v2/examples/orders_create_and_download_multiple_orders.py) (warning, we don't have a CI that guarantees this example runs, so you may run into a bug - a gap in our current testing / documentation design)

**Comment by sgillies** [comment]
I don't see any testing limitations. The mock library and pytest-asyncio give us all we need for unit testing. My coverage tests in #376 show this. For tests that require a fake service, pytest-aiohttp looks comparable to respx.

One thing I really like about aiohttp is that `await resp.json()` works reliably. Whereas with httpx we were having trouble with reading the response stream depending on the context due to changes in the API.

Aiohttp provides everything we need to download an order's assets concurrently. Currently, download_order() fetches assets serially https://github.com/planetlabs/planet-client-python/blob/v2/planet/clients/orders.py#L339. We'll need a more fancy implementation if we want to download and save files concurrently. Aiohttp will work well for that.
