### ISSUE TITLE
Temporarily rename "planet" CLI command in v2 to "planet2"

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#408]
The intent is to allow the pre-release v2 CLI to be tried in the same Python environments as v1.

**Comment by sgillies** [comment]
@jreiberkyle @mkshah605 what would you think about also temporarily renaming the package to "planet2" for the same reason. This is required to let a user have the old and pre-release packages installed properly in the same environment. This use case just came up :smile:

**Comment by jreiberkyle** [comment]
As the advocate for v2, my preference would be to rename the v1 package to "planet1" and keep v2 as "planet". My reasoning is that this will foster adoption of v2 because v2 will work 'by default' without having to rename it from "planet2" to "planet1". However, I am ultimately fine with whatever is decided.

**Comment by jreiberkyle** [comment]
that sounds great. and ultimately I'm up for whatever you, @cholmes, as the product owner, suggest

**Comment by sgillies** [comment]
We're not going to temporarily rename. The planet command in our first v2 pre-release will be "planet".
