### ISSUE TITLE
Refactor download checksum validation

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#521]
Before we finalize the Python API for 2.0, I'd like to separate the download validation, where we compare asset checksums to values in their accompanying manifest, from the orders client so that it's more generally available to users. There are use cases that don't need an orders client, such as re-validating the data after copying it to another computer.

**Comment by mkshah605** [comment]
TODO: Elevate checksum functionality

Currently the checksum functionality sits within the client. Move it out and consider how its use would be impacted if used outside the download order context.

Thoughts from @jreiberkyle :
"Since the user can call this function directly, as it is not a private function just being used by download_order anymore, I would consider usage scenarios and look at adding a bit of defensive logic. For example, I am curious what happens if checksum is an invalid entry like checksum='foobar'. Additionally, the user could call this function with arbitrary entries in filenames. I am curious what happens if one or more of the entries in filenames is not contained within manifest_data. Also what happens if an entry in filenames does not exist? These scenarios may be good candidates for raising an exception. Since this logic is no longer contained within a client, it may make sense to use a PlanetError instead of a ClientError (and catch and re-raise in download_order as a ClientError).

It also may make sense to add tests for these scenarios. The tests can test validate_checksum directly."

[See this ticket for reference](https://github.com/planetlabs/planet-client-python/pull/474)
