### ISSUE TITLE
Include list of reasonable options in `--help`

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#524]
Before we release we should go through all our `--help` documentation and make sure that we make it as self-documenting as possible, especially the places where there a handful of options that people would use. Right now in orders create it says:

```
Options:
  --name TEXT                     [required]
  --id TEXT                       One or more comma-separated item IDs
                                  [required]
  --bundle [analytic|analytic_udm2|analytic_3b_udm2|analytic_5b|analytic_5b_udm2|analytic_8b_udm2|visual|uncalibrated_dn|uncalibrated_dn_udm2|basic_analytic|basic_analytic_udm2|basic_analytic_8b_udm2|basic_uncalibrated_dn|basic_uncalibrated_dn_udm2|analytic_sr|analytic_sr_udm2|analytic_8b_sr_udm2|basic_uncalibrated_dn_nitf|basic_uncalibrated_dn_nitf_udm2|basic_analytic_nitf|basic_analytic_nitf_udm2|basic_panchromatic|basic_panchromatic_dn|panchromatic|panchromatic_dn|panchromatic_dn_udm2|pansharpened|pansharpened_udm2|basic_l1a_dn]
                                  Specify bundle  [required]
  --item-type TEXT                Specify an item type  [required]
  --email                         Send email notification when Order is
                                  complete
  --cloudconfig FILENAME          Cloud delivery config json file.
  --clip FILENAME                 Clip GeoJSON file.
  --tools FILENAME                Toolchain json file.
  --pretty                        Format JSON output.
  --help                          Show this message and exit.
```

It's a bit weird, since the bundle one shows me all the options, but item-type I need to go online to look up. There are actually less item-types than bundles, so it'd be easier to list. I'm also not totally sure if bundle is super useful as such a long list - it might make sense to try to shorten that to the 'main' ones and provide a link to the full list.

We should audit all the commands to ensure that if there are options that actually have a limited number of choices then we show them to the user right there instead of making them search the docs.

**Comment by jreiberkyle** [comment]
@cholmes yeah this is addressing the "we should audit all commands part", I'll definitely be getting into orders and subscriptions as well. I wasn't able to get the bonus part working with the click CLI, it doesn't allow for looking at the other arguments (aka ITEM_TYPE) in the part where a missing argument is dealt with. So, I plan to go with baseline for now. 

Would you prefer these lists to be in the option documentation - as it is in `planet orders request`, or below the options, as it is in `planet data asset-download`? It is below the options in `planet data asset-download` because the entries are arguments and that's the only place to programmatically populate the lists. If we move the options lists below as well it might improve consistency and improve readability.

**Comment by jreiberkyle** [comment]
ok since the main problem is fixed I'll close this.  we can look at how to improve bundles/assets documentation (which depends on item type) in the future. I think a better way to go would be to implement autocomplete.
