### ISSUE TITLE
Helper methods for subscriptions

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#614]
For the MVP of subscriptions we just have users directly form the entire json request, so we could ship something and iterate.

Now that it's out we should consider what we want to do to help users. To have one or more options like `planet data filter` or `planet order request`.

A user should be able to construct a decent subscription without having to get into JSON. When I have some time I'll map out some proposals, but just opening this to make sure we track and prioritize. 

#613 #601 are related - ideas on generating some of the JSON parts.

**Comment by cholmes** [comment]
The next step for this is likely to make a `planet subscription request`. There are four main JSON blocks - `source`, `tools`, `delivery` and `notifications`. 

A very naive first step could just be `planet subscription create --source source.json --tools tools.json --cloudconfig delivery.json and --notifications notifications.json. But that doesn't add so much value. The delivery and tools (#613 and #601) likely have nice re-use, but the 'source' feels different enough from `planet data filter` that we should probably just treat it separately instead of trying to reuse `data filter`. It requires geometry and date range, and it just overall feels a little bit different. 

So I think I'd propose the first one pass should not be a separate command for 'source'. So it'd be should be something like `planet data subscription --item-type PSScene --asset-types analytic --geom JSON --start-time 05/01/2022 --cloudconfig delivery.json`. With optional fields for tools, notifications, plus (source fields) end-time, rrule, and filter. And filter would ideally be able to take a `planet data filter` request, but probably strip out geom and date range filters (or perhaps just error, but give users a way to override it?)

**Comment by tbarsballe** [comment]
Most of the same things as for search and order, I'd say.

In particular, it'd be good if subscriptions helper methods wee structured in a way that makes it easy to move from a search+order based workflow to a subscriptions one, since beginners will usually be starting with that even if they eventually plan to move to subscriptions, as search is useful for narrowing down a final set of filters and previewing what that'll actually give you, and orders is the only way to get things locally.

Another thing that'd be very handy is some easy way to reuse geometry filter geometry for a clip tool, without having to specify it twice, since in basically all cases of using the clip tool you'll be using the same or similar geometry as in the filter. The vast majority of subscriptions users I've encountered are using the clip tool.

**Comment by cholmes** [comment]
> Another thing that'd be very handy is some easy way to reuse geometry filter geometry for a clip tool, without having to specify it twice, since in basically all cases of using the clip tool you'll be using the same or similar geometry as in the filter.

Are there cases where people would use different geometries for the search and the clip? Like wondering if we could just have `--geom JSON` and then just like `--clip` that would mean: 'use my geometry as the clip'. I guess we could have --clip with no arguments do that, and if it had an argument then we could use it.

**Comment by cholmes** [comment]
Just put up some ideas at https://github.com/planetlabs/planet-client-python/pull/689

**Comment by sgillies** [comment]
> Another thing that'd be very handy is some easy way to reuse geometry filter geometry for a clip tool, without having to specify it twice, since in basically all cases of using the clip tool you'll be using the same or similar geometry as in the filter. The vast majority of subscriptions users I've encountered are using the clip tool.

Note: the Subscriptions API is moving to a single geometry for AOI and clip.
