### ISSUE TITLE
Latest version of `planet` is raising a deprecation issue without solution 

### ISSUE THREAD

**Issue by 12rambau** [planetlabs/planet-client-python#630]
In my CI, the latest version of planet lib is raising a warning during the build: 

> WARNING: Cell printed to stderr:
[25](https://github.com/12rambau/sepal_ui/runs/7168669294?check_suite_focus=true#step:9:26)
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/planet/api/__init__.py:38: ClientV1DeprecationWarning: The planet.api module is deprecated and will be removed in version 2.0.0. For more details please see the discussion at https://github.com/planetlabs/planet-client-python/discussions.

The link is pointing to nowhere (I think it's due to the ".") but when I reached the discussions I son't manage to understand which one is dealing with this issue. Could you help ?

**Comment by cholmes** [comment]
Thanks for the feedback @12rambau!

We'll see about getting the link fixed, and perhaps linking to a more precise description of what's happening.

So it's more of a warning than an issue - just letting users know that in version 2.0.0 things are changing around a lot. Our hope is that it's a lot more pleasurable to use as a python developer, since v1 was more designed around the command-line. So you should be able to continue to use version 1.5.0 just fine. But when you want to upgrade then version 2.0.0 will not use the planet.api module, and you'll need to rewrite anything that uses it. 

We just released version 2.0.0-alpha.1, see https://github.com/planetlabs/planet-client-python#installation for how to install it. It'd be awesome to get your feedback on it. We're working on a guide to help people upgrade to 2.0.0, but the couple who have done it so far found it to be fairly straightforward.

**Comment by 12rambau** [comment]
Thanks a lot for your answer, As you open a specific issue for documenting the upgrade I think I can close this one
