### ISSUE TITLE
Report PL_API_KEY usage in `planet auth value`

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#643]
When debugging an early user's CLI it took some digging before I realized that PL_API_KEY was set and being used, since it didn't show up in `planet auth value`. It'd be good to give the user some indication what key will actually be used, over the one reported in `value`. My suggested route would be for `planet auth value` to say something like 'API Key set in PL_API_KEY environment variable:` and show that API key instead of the one they logged in with. But open to other ways to solve this.

**Comment by cholmes** [comment]
Should also warn on `planet auth init`

**Comment by tschaub** [comment]
I hit this same issue and agree that the CLI messages could make it easier to figure out what is going on.

When running `planet auth init` or `planet auth value`, if `PL_API_KEY` is set, it would be helpful if the CLI could say that it will be preferred over the `planet auth` configured value.  If `PL_API_KEY` is set to a different value, a "Warning: the PL_API_KEY environment variable is set to a different value than the one configured with `planet auth init`.  The PL_API_KEY environment variable has precedence and will be used instead of the configured key." would be helpful.

If something like this is printed from `planet auth value`, it should go to STDERR so that the value from STDOUT can still be used (e.g. `curl -u $(planet auth value): https://api.planet.com/compute/ops/orders/v2` should still work).

In addition, the message printed when `planet orders list` (or other requests) fails with a 401 could be more helpful.  The API responds with "API key not found" in the case of a 401.  From the perspective of a CLI user, this sounds like the CLI could not find my API key for use with the API.  Instead, a message like "Unable to list orders with the provided credentials" or something similar would be clearer.

**Comment by sgillies** [comment]
I think I found some low hanging fruit. At https://github.com/planetlabs/planet-client-python/blob/main/planet/cli/auth.py#L59 (planet auth value) we could get the active auth object (which is not necessarily from a file, planet.auth by design supports more sources than that) that we have stored in ctx and report based on its properties. That's a good start. To complement this we could add a source property to the APIKeyAuth class https://github.com/planetlabs/planet-client-python/blob/main/planet/auth.py#L198. With the new property, `planet auth value` could print something like `0123456789abcdef0123456789abcdef (from /home/me/.planet.json)`.

It's also worth warning about discrepancy between keys in the secret file and environment :+1:

**Comment by jreiberkyle** [comment]
Per #808, the CLI will only always use secret file for configuration. Therefore, this ticket (reporting PL_API_KEY usage in CLI) is no longer needed. The CLI will provide a helpful warning if PL_API_KEY is set when `planet auth login` or `planet auth init` are run.
