### ISSUE TITLE
Planet SDK Cli2-Orders v2: Error is displayed for the Search-id with request command

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#681]
**Environment**: planet, version 2.0a2

**Test Steps**
1. Create an order request with below command
`planet orders request --name test_order --bundle analytic --search-id 897802165e8d4bd587e342a4b399eda6 --clip - < aoi.geojson`

**Actual**: It is displaying error that search-id option is not available
```
Usage: planet orders request [OPTIONS]
Try 'planet orders request --help' for help.

Error: No such option: --search-id
```
**Expected**: It should create an order request

**Comment by cholmes** [comment]
We decided to not implement this route, since you can achieve it with an in-line search, see https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli-tutorial/#bringing-it-all-together

And this route requires creating a separate search and then referring to it. I'll try to remove this from the design doc.

**Comment by cholmes** [comment]
I'm going to close this issue, and we'll use https://github.com/planetlabs/planet-client-python/issues/388 to track the status of the core 'spec' on this stuff.
