### ISSUE TITLE
Planet Cli2 SDK: Orders v2: Unable to place a request with bundle option

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#729]
**Environment**: planet, version 2.0a6 dev

**Test steps**:
1. Place a request for orders v2 as below

planet orders request --name "CLI Order PSScene for product_bundle analytic_8b_sr_udm2" --id 20211222_122934_24_2447 --bundle visual --item-type PSScene

**Expected**: It should produce a request json without any error

**Actual**: It is displaying error as below as bundle type is not supported
```
Usage: planet orders request [OPTIONS] ITEM_TYPE BUNDLE
Try 'planet orders request --help' for help.

Error: No such option: --bundle
```

**Comment by jreiberkyle** [comment]
The issue is that you are using the `--bundle` flag, but in this version bundle is a positional argument. Retry with item type and bundle as positional arguments

`planet orders request --name "CLI Order PSScene for product_bundle analytic_8b_sr_udm2" --id 20211222_122934_24_2447 PSScene visual`

by the way, when 2.0a6 is released the UI should go back to flags instead of positional args, see #736

**Comment by cholmes** [comment]
> by the way, when 2.0a6 is released the UI should go back to flags instead of positional args, see https://github.com/planetlabs/planet-client-python/issues/736

To be clear, it'll be a single positional argument (id) and then the rest will be flags.
